version: '3.3'

services:
  verifier:
    # Local image must be built with `./gradlew bootBuildImage` in the eudi-srv-web-verifier-endpoint project
    image: net.openathletics.eudi/eudi-srv-web-verifier-endpoint:latest
    container_name: verifier-backend
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "http://119.8.212.190/"
      VERIFIER_RESPONSE_MODE: "DirectPost"

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:v0.9.1
    container_name: verifier-ui
    ports:
      - "4300:4300"
    environment:
      - DOMAIN_NAME=""
      - HOST_API="https://10.240.174.10"

  haproxy:
    image: haproxy:2.7.2
    container_name: haproxy
    ports:
      - "443:443"
    volumes:
      - ./haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy.pem:/etc/ssl/certs/mysite.pem
